import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import dynamic from "next/dynamic";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// Fixes: Hydration failed because the initial UI does not match what was rendered on the server.
// const DynamicContextProvider = dynamic(
//   () =>
//     import("@components/ContextProvider/ContextProvider").then(
//       (mod) => mod.ContextProvider
//     ),
//   {
//     ssr: false,
//   }
// );

export const metadata = {
  title: "DXN KATNI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
